import 'package:flutter/material.dart';

import '../../core/constants/app_colors.dart';
import '../../core/constants/app_sizes.dart';

class _LegalSection {
  final String titleEn;
  final String titleAr;
  final String bodyEn;
  final String bodyAr;
  const _LegalSection({
    required this.titleEn,
    required this.titleAr,
    required this.bodyEn,
    required this.bodyAr,
  });
}

/// ملحوظة: المحتوى ده مسودة قانونية مبدئية عامة، مبنية على طبيعة نشاط
/// Flynoom الفعلية (منصة وسيطة/aggregator، مش مالكة لأسطول سيارات أو
/// فنادق أو طائرات). لازم تتراجع من محامٍ مرخّص في ميشيغان (أو أي
/// ولاية تانية عندها Seller of Travel requirements زي كاليفورنيا/
/// فلوريدا) قبل النشر الفعلي أو قبول حجوزات حقيقية.
class PrivacyNoticePage extends StatelessWidget {
  const PrivacyNoticePage({super.key});

  static const String _lastUpdatedEn = 'September 1, 2026';
  static const String _lastUpdatedAr = '1 سبتمبر 2026';

  static const List<_LegalSection> _sections = [
    _LegalSection(
      titleEn: '1. Introduction',
      titleAr: '1. مقدمة',
      bodyEn:
      'This Privacy Notice explains how Flynoom ("Flynoom", "we", "us") collects, uses, shares, and protects information when you use our website and mobile application (the "Service"). Flynoom is a travel booking marketplace that lets you search and book flights, hotel stays, and other travel-related services supplied by third-party providers. By using the Service, you agree to the practices described in this notice.',
      bodyAr:
      'يوضح إشعار الخصوصية هذا الطريقة التي تجمع بها Flynoom ("Flynoom" أو "نحن") المعلومات وتستخدمها وتشاركها وتحميها عند استخدامك لموقعنا الإلكتروني وتطبيقنا (يُشار إليهما بـ"الخدمة"). Flynoom منصة وسيطة لحجوزات السفر تتيح لك البحث عن رحلات الطيران والإقامات الفندقية وخدمات سفر أخرى يقدّمها مزوّدون خارجيون وحجزها. باستخدامك للخدمة، فإنك توافق على الممارسات الموضحة في هذا الإشعار.',
    ),
    _LegalSection(
      titleEn: '2. Information We Collect',
      titleAr: '2. المعلومات التي نجمعها',
      bodyEn:
      'We collect information you provide directly (name, email, phone number, passport details for bookings, travel preferences), information generated by your use of the Service (search history, booking history, device identifiers, approximate location when you enable location services for features like "flights from your nearest city"), and information from third parties who fulfill your bookings (airlines via Duffel, hotel suppliers via HotelBeds) and our payment processor (Stripe). We do not store your full payment card number; Stripe processes and stores payment details under its own security standards.',
      bodyAr:
      'نجمع المعلومات التي تقدّمها مباشرة (الاسم، البريد الإلكتروني، رقم الهاتف، بيانات جواز السفر عند الحجز، تفضيلات السفر)، والمعلومات الناتجة عن استخدامك للخدمة (سجل البحث، سجل الحجوزات، معرّفات الجهاز، الموقع التقريبي عند تفعيل خدمات الموقع لميزات مثل "رحلات من أقرب مدينة لك")، والمعلومات الواردة من أطراف ثالثة تُنفّذ حجوزاتك (شركات الطيران عبر Duffel، مزوّدو الفنادق عبر HotelBeds) ومعالج المدفوعات (Stripe). نحن لا نخزّن رقم بطاقة الدفع الكامل؛ يتولى Stripe معالجة وتخزين بيانات الدفع وفق معاييره الأمنية الخاصة.',
    ),
    _LegalSection(
      titleEn: '3. How We Use Information',
      titleAr: '3. كيف نستخدم المعلومات',
      bodyEn:
      'We use collected information to process bookings and payments, communicate booking confirmations and updates, provide customer support, personalize search results (e.g. nearby destinations), detect and prevent fraud, comply with legal obligations, and improve the Service. We may send you promotional communications about deals and loyalty rewards; you can opt out at any time.',
      bodyAr:
      'نستخدم المعلومات التي نجمعها لمعالجة الحجوزات والمدفوعات، وإرسال تأكيدات الحجز وتحديثاته، وتقديم الدعم الفني، وتخصيص نتائج البحث (مثل الوجهات القريبة)، واكتشاف الاحتيال ومنعه، والامتثال للالتزامات القانونية، وتحسين الخدمة. قد نرسل لك مراسلات ترويجية عن العروض ومكافآت الولاء؛ ويمكنك إلغاء الاشتراك في أي وقت.',
    ),
    _LegalSection(
      titleEn: '4. Sharing With Third Parties',
      titleAr: '4. المشاركة مع أطراف ثالثة',
      bodyEn:
      'Because Flynoom operates as a booking marketplace, we necessarily share the booking information you provide with the relevant airline, hotel, or supplier so they can fulfill your reservation. We also share information with service providers who support our operations, including Supabase (authentication and database hosting), Stripe (payment processing), Duffel (flight search and booking), and HotelBeds (hotel search and booking). We do not sell your personal information to third parties for their own marketing purposes.',
      bodyAr:
      'بما أن Flynoom تعمل كمنصة وسيطة للحجوزات، فإننا بالضرورة نشارك بيانات الحجز التي تقدّمها مع شركة الطيران أو الفندق أو المزوّد المعني حتى يتمكنوا من تنفيذ حجزك. كما نشارك المعلومات مع مزوّدي خدمات يدعمون عملياتنا، منهم Supabase (المصادقة واستضافة قاعدة البيانات)، وStripe (معالجة المدفوعات)، وDuffel (بحث وحجز الرحلات)، وHotelBeds (بحث وحجز الفنادق). نحن لا نبيع معلوماتك الشخصية لأطراف ثالثة لأغراضهم التسويقية الخاصة.',
    ),
    _LegalSection(
      titleEn: '5. Data Retention',
      titleAr: '5. الاحتفاظ بالبيانات',
      bodyEn:
      'We retain booking and account information for as long as necessary to provide the Service, comply with legal and tax obligations, resolve disputes, and enforce our agreements. You may request deletion of your account data at any time, subject to records we are legally required to retain (e.g. transaction records).',
      bodyAr:
      'نحتفظ ببيانات الحجز والحساب طالما لزم الأمر لتقديم الخدمة، والامتثال للالتزامات القانونية والضريبية، وحل النزاعات، وتطبيق اتفاقياتنا. يمكنك طلب حذف بيانات حسابك في أي وقت، مع مراعاة السجلات التي يُلزمنا القانون بالاحتفاظ بها (مثل سجلات المعاملات).',
    ),
    _LegalSection(
      titleEn: '6. Your Privacy Rights',
      titleAr: '6. حقوقك المتعلقة بالخصوصية',
      bodyEn:
      'Depending on where you live, you may have rights to access, correct, delete, or export your personal information, and to opt out of certain data sales or sharing. California residents have rights under the California Consumer Privacy Act (CCPA); residents of the EU/UK have rights under GDPR-equivalent frameworks where applicable. To exercise any of these rights, contact us using the details below.',
      bodyAr:
      'حسب مكان إقامتك، قد يكون لك الحق في الوصول إلى معلوماتك الشخصية أو تصحيحها أو حذفها أو تصديرها، وكذلك حق الاعتراض على بيع أو مشاركة بيانات معينة. يتمتع سكان كاليفورنيا بحقوق بموجب قانون خصوصية المستهلك في كاليفورنيا (CCPA)، وقد يتمتع سكان الاتحاد الأوروبي والمملكة المتحدة بحقوق مماثلة بموجب اللوائح المعمول بها. لممارسة أي من هذه الحقوق، تواصل معنا عبر بيانات التواصل أدناه.',
    ),
    _LegalSection(
      titleEn: '7. Cookies and Tracking Technologies',
      titleAr: '7. ملفات تعريف الارتباط وتقنيات التتبع',
      bodyEn:
      'Our website may use cookies and similar technologies to remember your preferences, keep you signed in, and understand how the Service is used. You can control cookies through your browser settings; disabling them may limit some features.',
      bodyAr:
      'قد يستخدم موقعنا الإلكتروني ملفات تعريف الارتباط (الكوكيز) وتقنيات مشابهة لحفظ تفضيلاتك، وإبقائك مسجّل الدخول، وفهم كيفية استخدام الخدمة. يمكنك التحكم في الكوكيز من خلال إعدادات متصفحك؛ وقد يؤدي تعطيلها إلى تقييد بعض الميزات.',
    ),
    _LegalSection(
      titleEn: "8. Children's Privacy",
      titleAr: '8. خصوصية الأطفال',
      bodyEn:
      'The Service is not directed to children under 18, and we do not knowingly collect personal information from children. If you believe a child has provided us with personal information, contact us so we can remove it.',
      bodyAr:
      'الخدمة غير موجّهة للأطفال دون سن 18 عامًا، ولا نجمع عن قصد معلومات شخصية من الأطفال. إذا كنت تعتقد أن طفلًا قدّم لنا معلومات شخصية، تواصل معنا لإزالتها.',
    ),
    _LegalSection(
      titleEn: '9. International Data Transfers',
      titleAr: '9. نقل البيانات الدولي',
      bodyEn:
      'Because our suppliers and service providers operate globally, your information may be processed in countries other than your own, including the United States. We take reasonable steps to ensure such transfers are protected consistent with this notice.',
      bodyAr:
      'نظرًا لأن مزوّدينا وشركاءنا يعملون على مستوى عالمي، فقد تُعالَج معلوماتك في دول غير دولتك، بما في ذلك الولايات المتحدة. نتخذ خطوات معقولة لضمان حماية عمليات النقل هذه بما يتوافق مع هذا الإشعار.',
    ),
    _LegalSection(
      titleEn: '10. Data Security',
      titleAr: '10. أمان البيانات',
      bodyEn:
      'We use reasonable administrative, technical, and physical safeguards designed to protect your information. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.',
      bodyAr:
      'نستخدم إجراءات إدارية وتقنية ومادية معقولة مصمّمة لحماية معلوماتك. لا توجد طريقة نقل أو تخزين آمنة تمامًا، ولا يمكننا ضمان أمان مطلق.',
    ),
    _LegalSection(
      titleEn: '11. Changes to This Notice',
      titleAr: '11. تعديلات على هذا الإشعار',
      bodyEn:
      'We may update this Privacy Notice from time to time. Material changes will be reflected by updating the "Last updated" date above, and where required by law, we will provide additional notice.',
      bodyAr:
      'قد نقوم بتحديث إشعار الخصوصية هذا من وقت لآخر. سيتم توضيح التغييرات الجوهرية بتحديث تاريخ "آخر تحديث" أعلاه، وسنقدّم إشعارًا إضافيًا حيثما يتطلب القانون ذلك.',
    ),
    _LegalSection(
      titleEn: '12. How to Delete Your Account',
      titleAr: '12. كيف تحذف حسابك',
      bodyEn:
      'To delete your Flynoom account and associated personal data, send an email to support@flynoom.com from your registered email address with the subject line "Account Deletion Request", including the email or phone number linked to your account. We will process your request and delete your account and personal data within 30 days, except for records we are legally required to retain (e.g. transaction and tax records) as described in Section 5 (Data Retention). You may also request deletion of specific data without deleting your entire account by using the same email address with the subject "Data Deletion Request".',
      bodyAr:
      'لحذف حسابك في Flynoom وبياناتك الشخصية المرتبطة به، أرسل بريدًا إلكترونيًا إلى support@flynoom.com من بريدك الإلكتروني المسجّل، مع كتابة "طلب حذف الحساب" في عنوان الرسالة، وذكر البريد الإلكتروني أو رقم الهاتف المرتبط بحسابك. سنقوم بمعالجة طلبك وحذف حسابك وبياناتك الشخصية خلال 30 يومًا، باستثناء السجلات التي يُلزمنا القانون بالاحتفاظ بها (مثل سجلات المعاملات والسجلات الضريبية) كما هو موضح في القسم 5 (الاحتفاظ بالبيانات). يمكنك أيضًا طلب حذف بيانات معينة دون حذف كامل حسابك باستخدام نفس البريد الإلكتروني مع كتابة "طلب حذف البيانات" في العنوان.',
    ),
    _LegalSection(
      titleEn: '13. Contact Us',
      titleAr: '13. تواصل معنا',
      bodyEn:
      'If you have questions about this Privacy Notice or wish to exercise your privacy rights, contact us through the Customer Service page in the app, or by email at support@flynoom.com.',
      bodyAr:
      'إذا كانت لديك أسئلة حول إشعار الخصوصية هذا أو ترغب في ممارسة حقوقك المتعلقة بالخصوصية، تواصل معنا عبر صفحة خدمة العملاء داخل التطبيق، أو عبر البريد الإلكتروني support@flynoom.com.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final isArabic = Localizations.localeOf(context).languageCode == 'ar';

    return Scaffold(
      appBar: AppBar(
        title: Text(isArabic ? 'إشعار الخصوصية' : 'Privacy Notice'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSizes.md),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 800),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  isArabic ? 'إشعار الخصوصية' : 'Privacy Notice',
                  style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 4),
                Text(
                  isArabic ? 'آخر تحديث: $_lastUpdatedAr' : 'Last updated: $_lastUpdatedEn',
                  style: const TextStyle(color: AppColors.textSecondary, fontSize: 13),
                ),
                const SizedBox(height: AppSizes.lg),
                for (final s in _sections) ...[
                  Text(
                    isArabic ? s.titleAr : s.titleEn,
                    style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w600),
                  ),
                  const SizedBox(height: 6),
                  Text(
                    isArabic ? s.bodyAr : s.bodyEn,
                    style: const TextStyle(fontSize: 14, height: 1.6, color: AppColors.textSecondary),
                  ),
                  const SizedBox(height: AppSizes.lg),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}